import { SlashCommandBuilder } from 'discord.js';
import type { ChatInputCommandInteraction } from 'discord.js';
import type { CommandDef } from '../../../types';
import { ask, NetworkError, SafetyError, RateLimitError, DailyLimitError, type Provider } from '../router';
import { checkCooldown, remainingCooldown } from '../../../services/rateLimit';
import { remaining } from '../../../services/usageLimit';
import { getAIConfig, getModelDisplayInfo } from '../../../services/aiConfig';
import { isVertexMode } from '../providers/anthropic';
import { logger } from '../../../services/logger';

const BASE_COOLDOWN_MS = 8_000;
const MAX_COOLDOWN_MS  = 60_000;
const LEARN_MORE = 'https://stealthylabs.eu/docs/specter-bot';

let askCooldown    = BASE_COOLDOWN_MS;
let lastAskError   = 0;

function getAskCooldown(): number {
  if (Date.now() - lastAskError > 300_000) askCooldown = BASE_COOLDOWN_MS;
  return askCooldown;
}

const askCommand: CommandDef = {
  data: new SlashCommandBuilder()
    .setName('ask')
    .setDescription('Ask a question to Claude or Gemini')
    .addStringOption((opt) =>
      opt.setName('question').setDescription('Your question').setRequired(true)
    )
    .addStringOption((opt) =>
      opt
        .setName('provider')
        .setDescription('AI provider to use')
        .setRequired(false)
        .addChoices(
          { name: 'Auto (default)', value: 'auto' },
          { name: 'Claude (Anthropic)', value: 'claude' },
          { name: 'Gemini (Google)', value: 'gemini' }
        )
    )
    .addStringOption((opt) =>
      opt
        .setName('lang')
        .setDescription('Response language')
        .setRequired(false)
        .addChoices(
          { name: 'English',    value: 'English' },
          { name: 'French',     value: 'French' },
          { name: 'Spanish',    value: 'Spanish' },
          { name: 'German',     value: 'German' },
          { name: 'Japanese',   value: 'Japanese' },
          { name: 'Korean',     value: 'Korean' },
          { name: 'Chinese',    value: 'Chinese' },
          { name: 'Portuguese', value: 'Portuguese' },
          { name: 'Russian',    value: 'Russian' },
          { name: 'Arabic',     value: 'Arabic' },
        )
    ) as SlashCommandBuilder,

  async execute(interaction: ChatInputCommandInteraction): Promise<void> {
    const cd = getAskCooldown();
    if (checkCooldown('ask', interaction.user.id, cd)) {
      const secs = (remainingCooldown('ask', interaction.user.id, cd) / 1000).toFixed(0);
      const extra = cd > BASE_COOLDOWN_MS ? ' (API busy, cooldown extended)' : '';
      await interaction.reply({ content: `Cooldown active - try again in ${secs}s.${extra}`, ephemeral: true });
      return;
    }

    await interaction.deferReply();

    const question = interaction.options.getString('question', true);
    const provider = (interaction.options.getString('provider') ?? 'auto') as Provider;
    const lang     = interaction.options.getString('lang');

    try {
      const finalPrompt = lang ? `[Respond in ${lang}] ${question}` : question;
      const result = await ask(
        interaction.guildId ?? 'dm',
        interaction.user.id,
        finalPrompt,
        provider
      );

      const { name, source } = getModelDisplayInfo(
        result.provider,
        result.model,
        result.provider === 'claude' && isVertexMode()
      );

      const parts: string[] = [];

      // Daily quota (Claude + Gemini)
      const left = remaining(interaction.user.id, result.model);
      if (left !== null) parts.push(`${left} req left today`);

      // Token usage
      if (result.tokenUsage) {
        const u = result.tokenUsage;
        const total = u.inputTokens + u.outputTokens;
        let tokenStr = `${total} tokens (${u.inputTokens} in · ${u.outputTokens} out)`;
        if (u.cacheReadTokens && u.cacheReadTokens > 0) {
          tokenStr += ` · ${u.cacheReadTokens} cached`;
        }
        parts.push(tokenStr);
      }

      parts.push(`[Learn more](${LEARN_MORE})`);

      const text = result.text.length > 1900 ? result.text.slice(0, 1897) + '...' : result.text;

      const content = [
        text,
        `-# Generated by **${name}** (${source}). AI can make mistakes. • ${parts.join(' • ')}`,
      ].join('\n');

      askCooldown = Math.max(BASE_COOLDOWN_MS, Math.floor(askCooldown * 0.7));
      await interaction.editReply({ content });
    } catch (err) {
      lastAskError = Date.now();
      askCooldown = Math.min(MAX_COOLDOWN_MS, askCooldown * 2);
      logger.error({ err }, '/ask failed (cooldown now %ds)', askCooldown / 1000);
      await interaction.editReply(errorMessage(err));
    }
  },
};

function errorMessage(err: unknown): string {
  if (err instanceof DailyLimitError) {
    return `Daily limit reached for **${err.model}** (${err.limit} requests/day). Resets at midnight UTC.`;
  }
  if (err instanceof RateLimitError) return 'Too many requests, please try again in a few seconds.';
  if (err instanceof SafetyError) return 'This request could not be processed.';
  if (err instanceof NetworkError) return 'The AI service is temporarily unavailable.';
  const msg = err instanceof Error ? err.message : String(err);
  if (msg.includes('not available')) return msg;
  return 'The AI service is temporarily unavailable.';
}

export default askCommand;
