import type { Client } from 'discord.js';
import { Events } from 'discord.js';
import type { BotModule } from '../../types';
// Lightweight availability checks — no SDK imports at startup
import {
  claudeAvailable, geminiAvailable, openaiAvailable, ollamaAvailable, anyProviderAvailable,
} from '../../services/ai/availability';
import { ask } from '../../services/ai/router';
import { getModelDisplayInfo } from '../../services/aiConfig';
import { remaining } from '../../services/usageLimit';
import { logger } from '../../services/logger';
import askCommand from './commands/ask';
import summarize from './commands/summarize';
import setmodel from './commands/setmodel';
import nanobanana from './commands/nanobanana';
import translate from './commands/translate';
import roast from './commands/roast';

const ollamaEnabled = ollamaAvailable();
const openaiEnabled = openaiAvailable();
const hasAnyProvider = anyProviderAvailable();

if (!hasAnyProvider) {
  logger.warn('ai module: No AI provider keys found - module disabled');
} else {
  if (claudeAvailable()) {
    const vertex = !!process.env.GOOGLE_CLOUD_PROJECT;
    const via = vertex ? 'via Vertex AI (GCP)' : 'via direct API';
    logger.info('ai module: Claude provider enabled (%s)', via);
  }
  if (geminiAvailable()) logger.info('ai module: Gemini provider enabled');
  else logger.info('ai module: /nanobanana generation disabled (no GOOGLE_AI_API_KEY)');
  if (openaiEnabled) logger.info('ai module: OpenAI provider enabled');
  if (ollamaEnabled) logger.info('ai module: Ollama provider enabled (local)');
}

import vision from './commands/vision';
import catchup from './commands/catchup';
import tldr from './commands/tldr';
import cloudai from './commands/cloudai';
import localai from './commands/localai';
import code from './commands/code';
import persona from './commands/persona';
import explain from './commands/explain';
import debate from './commands/debate';
import llm from './commands/llm';

const commands = [askCommand, summarize, setmodel, nanobanana, translate, roast, vision, catchup, tldr, cloudai, code, persona, explain, debate, llm];

// Only register /localai when Ollama is configured
if (ollamaEnabled) commands.push(localai);

const LEARN_MORE = 'https://stealthylabs.eu/docs/arklay-bot';

const aiModule: BotModule = {
  name: 'ai',
  enabled: hasAnyProvider,
  commands,

  async onLoad(client: Client): Promise<void> {
    // Reply-to-bot conversation: when someone replies to a bot AI message, continue the conversation
    client.on(Events.MessageCreate, async (message) => {
      if (message.author.bot || !message.guild || !message.content) return;
      if (!message.reference?.messageId) return;

      let refMsg;
      try {
        refMsg = await message.channel.messages.fetch(message.reference.messageId);
      } catch { return; }

      if (refMsg.author.id !== client.user?.id) return;

      const hasAIFooter = refMsg.content.includes('Generated by') || refMsg.content.includes('AI can make mistakes');
      if (!hasAIFooter) return;

      try {
        await message.channel.sendTyping();
        const result = await ask(
          message.guildId!,
          message.author.id,
          message.content,
          'auto',
          false,
        );

        const { name, source } = getModelDisplayInfo(
          result.provider,
          result.model,
          result.provider === 'claude' && !!process.env.GOOGLE_CLOUD_PROJECT
        );

        const parts: string[] = [];
        const left = remaining(message.author.id, result.model);
        if (left !== null) parts.push(`${left} req left today`);
        if (result.tokenUsage) {
          const total = result.tokenUsage.inputTokens + result.tokenUsage.outputTokens;
          parts.push(`${total} tokens (${result.tokenUsage.inputTokens} in \u00b7 ${result.tokenUsage.outputTokens} out)`);
        }
        parts.push(`[Learn more](${LEARN_MORE})`);

        const text = result.text.length > 1900 ? result.text.slice(0, 1897) + '...' : result.text;
        const content = [
          text,
          `-# Generated by **${name}** (${source}). AI can make mistakes. \u2022 ${parts.join(' \u2022 ')}`,
        ].join('\n');

        await message.reply({ content });
      } catch (err) {
        logger.error({ err }, 'AI reply-to failed');
      }
    });

    logger.info('ai module: reply-to-bot conversation enabled');
  },
};

export default aiModule;
